name       : libgnomeui
version    : 2.24.5
release    : 11
source     :
    - https://download.gnome.org/sources/libgnomeui/2.24/libgnomeui-2.24.5.tar.bz2 : ae352f2495889e65524c979932c909f4629a58e64290fb0c95333373225d3c0f
license    : GPL-2.0-only
component  : programming.library
summary    : User Interface library for GNOME
description: |
    User Interface library for GNOME
builddeps  :
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(libbonoboui-2.0)
    - pkgconfig(libglade-2.0)
    - pkgconfig(popt)
    - pkgconfig(sm)
    - intltool
setup      : |
    %patch -p1 < $pkgfiles/glib-2.54-ftbfs.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
